version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'forhad@1234'
      MYSQL_DATABASE: PhoneBook
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis-cache-phoneBook
    restart: always
    ports:
      - "6382:6379"
    networks:
      - spring-network
    volumes:
      - redis_data:/data

networks:
  spring-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
